# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_geomeditor.ui'
#
# Created: Wed Feb 13 07:12:34 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_GeomEditor(object):
    def setupUi(self, GeomEditor):
        GeomEditor.setObjectName(_fromUtf8("GeomEditor"))
        GeomEditor.resize(571, 549)
        self.gridLayout_4 = QtGui.QGridLayout(GeomEditor)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 4, 2, 1, 1)
        self.w5 = QtGui.QWidget(GeomEditor)
        self.w5.setObjectName(_fromUtf8("w5"))
        self.gridLayout_2 = QtGui.QGridLayout(self.w5)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.copyButton = QtGui.QPushButton(self.w5)
        self.copyButton.setObjectName(_fromUtf8("copyButton"))
        self.gridLayout_2.addWidget(self.copyButton, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(223, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 1, 1, 1)
        self.resetButton = QtGui.QPushButton(self.w5)
        self.resetButton.setObjectName(_fromUtf8("resetButton"))
        self.gridLayout_2.addWidget(self.resetButton, 0, 2, 1, 1)
        self.applyButton = QtGui.QPushButton(self.w5)
        self.applyButton.setObjectName(_fromUtf8("applyButton"))
        self.gridLayout_2.addWidget(self.applyButton, 0, 3, 1, 1)
        self.gridLayout_4.addWidget(self.w5, 5, 0, 1, 3)
        self.geomTextEdit = QtGui.QTextEdit(GeomEditor)
        self.geomTextEdit.setObjectName(_fromUtf8("geomTextEdit"))
        self.gridLayout_4.addWidget(self.geomTextEdit, 1, 0, 1, 3)
        self.w2 = QtGui.QWidget(GeomEditor)
        self.w2.setObjectName(_fromUtf8("w2"))
        self.gridLayout_6 = QtGui.QGridLayout(self.w2)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.geomStatusLabel = QtGui.QLabel(self.w2)
        self.geomStatusLabel.setText(_fromUtf8(""))
        self.geomStatusLabel.setObjectName(_fromUtf8("geomStatusLabel"))
        self.gridLayout_6.addWidget(self.geomStatusLabel, 0, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem2, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.w2, 2, 0, 1, 3)
        self.w0 = QtGui.QWidget(GeomEditor)
        self.w0.setObjectName(_fromUtf8("w0"))
        self.gridLayout_3 = QtGui.QGridLayout(self.w0)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.featureEdit = QtGui.QLineEdit(self.w0)
        self.featureEdit.setEnabled(False)
        self.featureEdit.setObjectName(_fromUtf8("featureEdit"))
        self.gridLayout_3.addWidget(self.featureEdit, 0, 1, 1, 1)
        self.layerLabel = QtGui.QLabel(self.w0)
        self.layerLabel.setObjectName(_fromUtf8("layerLabel"))
        self.gridLayout_3.addWidget(self.layerLabel, 0, 0, 1, 1)
        self.displayCombo = QtGui.QComboBox(self.w0)
        self.displayCombo.setObjectName(_fromUtf8("displayCombo"))
        self.displayCombo.addItem(_fromUtf8(""))
        self.displayCombo.addItem(_fromUtf8(""))
        self.displayCombo.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.displayCombo, 0, 4, 1, 1)
        self.label = QtGui.QLabel(self.w0)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 0, 3, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 0, 2, 1, 1)
        self.gridLayout_4.addWidget(self.w0, 0, 0, 1, 3)
        self.w3 = QtGui.QWidget(GeomEditor)
        self.w3.setObjectName(_fromUtf8("w3"))
        self.gridLayout = QtGui.QGridLayout(self.w3)
        self.gridLayout.setMargin(0)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.gridLayout_4.addWidget(self.w3, 3, 0, 1, 3)
        self.sketchBox = QgsCollapsibleGroupBoxBasic(GeomEditor)
        self.sketchBox.setCheckable(True)
        self.sketchBox.setProperty("collapsed", True)
        self.sketchBox.setObjectName(_fromUtf8("sketchBox"))
        self.gridLayout_7 = QtGui.QGridLayout(self.sketchBox)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.spinBox = QtGui.QSpinBox(self.sketchBox)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.gridLayout_7.addWidget(self.spinBox, 0, 3, 1, 1)
        self.spinBox_2 = QtGui.QSpinBox(self.sketchBox)
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.gridLayout_7.addWidget(self.spinBox_2, 1, 3, 1, 1)
        self.toolButton_4 = QtGui.QToolButton(self.sketchBox)
        self.toolButton_4.setText(_fromUtf8(""))
        self.toolButton_4.setObjectName(_fromUtf8("toolButton_4"))
        self.gridLayout_7.addWidget(self.toolButton_4, 1, 1, 1, 1)
        self.toolButton_2 = QtGui.QToolButton(self.sketchBox)
        self.toolButton_2.setText(_fromUtf8(""))
        self.toolButton_2.setObjectName(_fromUtf8("toolButton_2"))
        self.gridLayout_7.addWidget(self.toolButton_2, 0, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.sketchBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_7.addWidget(self.label_2, 0, 0, 1, 1)
        self.toolButton_3 = QtGui.QToolButton(self.sketchBox)
        self.toolButton_3.setText(_fromUtf8(""))
        self.toolButton_3.setObjectName(_fromUtf8("toolButton_3"))
        self.gridLayout_7.addWidget(self.toolButton_3, 1, 2, 1, 1)
        self.checkBox = QtGui.QCheckBox(self.sketchBox)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout_7.addWidget(self.checkBox, 1, 4, 1, 1)
        self.label_3 = QtGui.QLabel(self.sketchBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_7.addWidget(self.label_3, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.sketchBox, 4, 1, 1, 1)

        self.retranslateUi(GeomEditor)
        QtCore.QMetaObject.connectSlotsByName(GeomEditor)

    def retranslateUi(self, GeomEditor):
        GeomEditor.setWindowTitle(QtGui.QApplication.translate("GeomEditor", "Plain Geometry Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.copyButton.setText(QtGui.QApplication.translate("GeomEditor", "Copy to clipbaord", None, QtGui.QApplication.UnicodeUTF8))
        self.resetButton.setText(QtGui.QApplication.translate("GeomEditor", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.applyButton.setText(QtGui.QApplication.translate("GeomEditor", "Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.layerLabel.setText(QtGui.QApplication.translate("GeomEditor", "Feature", None, QtGui.QApplication.UnicodeUTF8))
        self.displayCombo.setItemText(0, QtGui.QApplication.translate("GeomEditor", "cells", None, QtGui.QApplication.UnicodeUTF8))
        self.displayCombo.setItemText(1, QtGui.QApplication.translate("GeomEditor", "WKT", None, QtGui.QApplication.UnicodeUTF8))
        self.displayCombo.setItemText(2, QtGui.QApplication.translate("GeomEditor", "WKB", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("GeomEditor", "Display format", None, QtGui.QApplication.UnicodeUTF8))
        self.sketchBox.setTitle(QtGui.QApplication.translate("GeomEditor", "Sketch geometry", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("GeomEditor", "Line style", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("GeomEditor", "sketch current point", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("GeomEditor", "Point style", None, QtGui.QApplication.UnicodeUTF8))

from qgis.gui import QgsCollapsibleGroupBoxBasic
