# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_geomeditor.ui'
#
# Created: Wed Jun 19 10:32:50 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_GeomEditor(object):
    def setupUi(self, GeomEditor):
        GeomEditor.setObjectName(_fromUtf8("GeomEditor"))
        GeomEditor.resize(487, 494)
        self.gridLayout_4 = QtGui.QGridLayout(GeomEditor)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 3, 2, 1, 1)
        self.w5 = QtGui.QWidget(GeomEditor)
        self.w5.setObjectName(_fromUtf8("w5"))
        self.gridLayout_2 = QtGui.QGridLayout(self.w5)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        spacerItem1 = QtGui.QSpacerItem(223, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 0, 1, 1)
        self.resetButton = QtGui.QPushButton(self.w5)
        self.resetButton.setObjectName(_fromUtf8("resetButton"))
        self.gridLayout_2.addWidget(self.resetButton, 0, 1, 1, 1)
        self.applyButton = QtGui.QPushButton(self.w5)
        self.applyButton.setObjectName(_fromUtf8("applyButton"))
        self.gridLayout_2.addWidget(self.applyButton, 0, 2, 1, 1)
        self.gridLayout_4.addWidget(self.w5, 4, 0, 1, 3)
        self.w2 = QtGui.QWidget(GeomEditor)
        self.w2.setObjectName(_fromUtf8("w2"))
        self.gridLayout_6 = QtGui.QGridLayout(self.w2)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.geomStatusLabel = QtGui.QLabel(self.w2)
        self.geomStatusLabel.setText(_fromUtf8(""))
        self.geomStatusLabel.setObjectName(_fromUtf8("geomStatusLabel"))
        self.gridLayout_6.addWidget(self.geomStatusLabel, 0, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem2, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.w2, 2, 0, 1, 3)
        self.w0 = QtGui.QWidget(GeomEditor)
        self.w0.setObjectName(_fromUtf8("w0"))
        self.gridLayout_3 = QtGui.QGridLayout(self.w0)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.featureEdit = QtGui.QLineEdit(self.w0)
        self.featureEdit.setEnabled(False)
        self.featureEdit.setObjectName(_fromUtf8("featureEdit"))
        self.gridLayout_3.addWidget(self.featureEdit, 0, 1, 1, 1)
        self.layerLabel = QtGui.QLabel(self.w0)
        self.layerLabel.setObjectName(_fromUtf8("layerLabel"))
        self.gridLayout_3.addWidget(self.layerLabel, 0, 0, 1, 1)
        self.displayCombo = QtGui.QComboBox(self.w0)
        self.displayCombo.setObjectName(_fromUtf8("displayCombo"))
        self.displayCombo.addItem(_fromUtf8(""))
        self.displayCombo.addItem(_fromUtf8(""))
        self.displayCombo.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.displayCombo, 0, 4, 1, 1)
        self.label = QtGui.QLabel(self.w0)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 0, 3, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 0, 2, 1, 1)
        self.gridLayout_4.addWidget(self.w0, 0, 0, 1, 3)
        self.sketchGeometry = QgsCollapsibleGroupBoxBasic(GeomEditor)
        self.sketchGeometry.setCheckable(True)
        self.sketchGeometry.setProperty("collapsed", True)
        self.sketchGeometry.setObjectName(_fromUtf8("sketchGeometry"))
        self.gridLayout_7 = QtGui.QGridLayout(self.sketchGeometry)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.widget = QtGui.QWidget(self.sketchGeometry)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_5 = QtGui.QGridLayout(self.widget)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.featureRubberColor = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.featureRubberColor.sizePolicy().hasHeightForWidth())
        self.featureRubberColor.setSizePolicy(sizePolicy)
        self.featureRubberColor.setMinimumSize(QtCore.QSize(30, 0))
        self.featureRubberColor.setText(_fromUtf8(""))
        self.featureRubberColor.setObjectName(_fromUtf8("featureRubberColor"))
        self.gridLayout_5.addWidget(self.featureRubberColor, 0, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_5.addWidget(self.label_2, 0, 0, 1, 1)
        self.pointRubberGroup = QtGui.QWidget(self.widget)
        self.pointRubberGroup.setObjectName(_fromUtf8("pointRubberGroup"))
        self.gridLayout_8 = QtGui.QGridLayout(self.pointRubberGroup)
        self.gridLayout_8.setMargin(0)
        self.gridLayout_8.setMargin(0)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.currentPointRubberIcon = QtGui.QComboBox(self.pointRubberGroup)
        self.currentPointRubberIcon.setObjectName(_fromUtf8("currentPointRubberIcon"))
        self.currentPointRubberIcon.addItem(_fromUtf8(""))
        self.currentPointRubberIcon.addItem(_fromUtf8(""))
        self.currentPointRubberIcon.addItem(_fromUtf8(""))
        self.currentPointRubberIcon.addItem(_fromUtf8(""))
        self.currentPointRubberIcon.addItem(_fromUtf8(""))
        self.gridLayout_8.addWidget(self.currentPointRubberIcon, 0, 1, 1, 1)
        self.displayPointRubber = QtGui.QCheckBox(self.pointRubberGroup)
        self.displayPointRubber.setChecked(True)
        self.displayPointRubber.setObjectName(_fromUtf8("displayPointRubber"))
        self.gridLayout_8.addWidget(self.displayPointRubber, 0, 0, 1, 1)
        self.currentPointRubberColor = QtGui.QLabel(self.pointRubberGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.currentPointRubberColor.sizePolicy().hasHeightForWidth())
        self.currentPointRubberColor.setSizePolicy(sizePolicy)
        self.currentPointRubberColor.setMinimumSize(QtCore.QSize(30, 0))
        self.currentPointRubberColor.setText(_fromUtf8(""))
        self.currentPointRubberColor.setObjectName(_fromUtf8("currentPointRubberColor"))
        self.gridLayout_8.addWidget(self.currentPointRubberColor, 0, 2, 1, 1)
        self.currentPointRubberSize = QtGui.QSpinBox(self.pointRubberGroup)
        self.currentPointRubberSize.setToolTip(_fromUtf8(""))
        self.currentPointRubberSize.setObjectName(_fromUtf8("currentPointRubberSize"))
        self.gridLayout_8.addWidget(self.currentPointRubberSize, 0, 3, 1, 1)
        self.gridLayout_5.addWidget(self.pointRubberGroup, 1, 0, 1, 5)
        self.featureRubberSize = QtGui.QDoubleSpinBox(self.widget)
        self.featureRubberSize.setToolTip(_fromUtf8(""))
        self.featureRubberSize.setDecimals(1)
        self.featureRubberSize.setMinimum(0.1)
        self.featureRubberSize.setMaximum(20.0)
        self.featureRubberSize.setSingleStep(0.2)
        self.featureRubberSize.setProperty("value", 0.6)
        self.featureRubberSize.setObjectName(_fromUtf8("featureRubberSize"))
        self.gridLayout_5.addWidget(self.featureRubberSize, 0, 4, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem4, 0, 1, 1, 1)
        self.gridLayout_7.addWidget(self.widget, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.sketchGeometry, 3, 1, 1, 1)
        self.editorContainer = QtGui.QWidget(GeomEditor)
        self.editorContainer.setObjectName(_fromUtf8("editorContainer"))
        self.gridLayout_4.addWidget(self.editorContainer, 1, 0, 1, 3)

        self.retranslateUi(GeomEditor)
        self.currentPointRubberIcon.setCurrentIndex(3)
        QtCore.QObject.connect(self.sketchGeometry, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.widget.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(GeomEditor)

    def retranslateUi(self, GeomEditor):
        GeomEditor.setWindowTitle(QtGui.QApplication.translate("GeomEditor", "Plain Geometry Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.resetButton.setText(QtGui.QApplication.translate("GeomEditor", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.applyButton.setText(QtGui.QApplication.translate("GeomEditor", "Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.layerLabel.setText(QtGui.QApplication.translate("GeomEditor", "Feature", None, QtGui.QApplication.UnicodeUTF8))
        self.displayCombo.setItemText(0, QtGui.QApplication.translate("GeomEditor", "cells", None, QtGui.QApplication.UnicodeUTF8))
        self.displayCombo.setItemText(1, QtGui.QApplication.translate("GeomEditor", "WKT", None, QtGui.QApplication.UnicodeUTF8))
        self.displayCombo.setItemText(2, QtGui.QApplication.translate("GeomEditor", "WKB", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("GeomEditor", "Display format", None, QtGui.QApplication.UnicodeUTF8))
        self.sketchGeometry.setTitle(QtGui.QApplication.translate("GeomEditor", "Sketch geometry", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("GeomEditor", "New geometry style", None, QtGui.QApplication.UnicodeUTF8))
        self.currentPointRubberIcon.setItemText(0, QtGui.QApplication.translate("GeomEditor", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.currentPointRubberIcon.setItemText(1, QtGui.QApplication.translate("GeomEditor", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.currentPointRubberIcon.setItemText(2, QtGui.QApplication.translate("GeomEditor", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.currentPointRubberIcon.setItemText(3, QtGui.QApplication.translate("GeomEditor", "□", None, QtGui.QApplication.UnicodeUTF8))
        self.currentPointRubberIcon.setItemText(4, QtGui.QApplication.translate("GeomEditor", "○", None, QtGui.QApplication.UnicodeUTF8))
        self.displayPointRubber.setText(QtGui.QApplication.translate("GeomEditor", "sketch current point in editor", None, QtGui.QApplication.UnicodeUTF8))

from qgis.gui import QgsCollapsibleGroupBoxBasic
